# Generated by Django 4.2.10 on 2024-03-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_alter_booking_check_in_alter_booking_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='all@iiti.ac.in', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default=9876543210, max_length=15),
        ),
    ]
