# Generated by Django 4.2.10 on 2024-03-23 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0007_alter_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('1', 'Basic'), ('2', 'Premium')], default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('number_of_rooms', models.PositiveIntegerField()),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('room_numbers', models.CharField(help_text='Enter room numbers separated by commas', max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('room_type', models.CharField(max_length=20)),
                ('payment_status', models.CharField(choices=[('1', 'Pending'), ('2', 'Done'), ('3', 'Pay Later')], default='1', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
