# Generated by Django 4.2.10 on 2024-03-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_room_rent_alter_room_category_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(choices=[('1', 'Basic'), ('2', 'Premium')], default='1', max_length=1),
        ),
    ]
