# Generated by Django 5.0.3 on 2024-03-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_alter_reservation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('txnid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('error_Message', models.TextField()),
                ('net_amount_debit', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('productinfo', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('addedon', models.DateTimeField()),
                ('encryptedPaymentId', models.CharField(max_length=255)),
                ('email', models.EmailField(default='all@iiti.ac.in', max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payuMoneyId', models.CharField(max_length=255)),
                ('mihpayid', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='institute_use',
            field=models.BooleanField(default=False),
        ),
    ]
