# Generated by Django 5.0.3 on 2024-03-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_alter_transaction_net_amount_debit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='failure', max_length=10),
        ),
    ]
