# Generated by Django 5.0.3 on 2024-03-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0013_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reservation_id',
            field=models.IntegerField(default=1),
        ),
    ]
