# Generated by Django 5.0.3 on 2024-03-29 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0014_transaction_reservation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reservation_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='reservation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hostel.reservation'),
        ),
    ]
