# Generated by Django 5.0.3 on 2024-04-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0016_reservation_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='verified',
            field=models.CharField(choices=[('1', 'Accepted'), ('2', 'Rejected'), ('3', 'Pending')], default='3', max_length=1),
        ),
    ]
