# Generated by Django 5.0.3 on 2024-04-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0017_alter_reservation_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='room',
            name='rent',
        ),
    ]
