# Generated by Django 5.0.3 on 2024-04-03 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0018_remove_reservation_room_type_remove_room_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='category',
        ),
    ]
