# Generated by Django 5.0.3 on 2024-04-03 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0019_remove_room_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
    ]
