# Generated by Django 5.0.3 on 2024-04-03 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0020_remove_room_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='verified',
            new_name='verified_status',
        ),
    ]
