# Generated by Django 5.0.3 on 2024-04-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0022_reservation_gst_reservation_length_of_stay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('1', 'Self'), ('2', 'Project')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='project_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='project_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
