# Generated by Django 5.0.3 on 2024-04-15 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0024_alter_transaction_productinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reservation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hostel.reservation'),
        ),
    ]
